// Core
import {Montserrat_Alternates} from "next/font/google";
// Styles
import "./globals.css";
// Types
import type {Metadata, NextPage} from "next";

const montserrat = Montserrat_Alternates({
    weight: ['400', '500', '600'],
    preload: true,
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout: NextPage<OnlyChildrenType> = ({children}) =>
    <html lang="en">
        <body className={montserrat['className']}>
            {children}
        </body>
    </html>

export default RootLayout;