// Core
import {Inter} from "next/font/google";
// Styles
import "./globals.css";
// Types
import type {Metadata, NextPage} from "next";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout: NextPage<OnlyChildrenType> = ({children}) =>
    <html lang="en">
        <body className={inter.className}>
            {children}
        </body>
    </html>

export default RootLayout;